### ISSUE TITLE
Не используется селектор

### ISSUE THREAD

**Issue by staskuban** [mornelytom/tour-of-heroes-mobile#1]
Ты объявила селектор но не используешь

https://github.com/mornelytom/tour-of-heroes-mobile/blob/9ad042be539229913356c88e66f33f312a52418f/src/shared/base/state/hero.state.ts#L23

```typescript
  this.heroes$ = this.store.select(state => state.heroes.heroes);
```

**Comment by mornelytom** [comment]
Исправлено в ветке feature/FM-49
