### ISSUE TITLE
Излишний код

### ISSUE THREAD

**Issue by staskuban** [mornelytom/tour-of-heroes-mobile#2]
У тебя есть метод getHeroes, используй его в store та реализация которая есть у тебя создает доп расходы на ресурсы и поддержку

https://github.com/mornelytom/tour-of-heroes-mobile/blob/9ad042be539229913356c88e66f33f312a52418f/src/app/hero.service.ts#L24

**Comment by mornelytom** [comment]
Исправлено в ветке feature/FM-49
